# Generated by Django 2.1.5 on 2019-01-12 10:06

from django.db import migrations, models
import django.db.models.deletion


def add_default_category(apps, *args, **kwargs):
    Category = apps.get_model('transactions', 'Category')
    Category.objects.create(name='Default')


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190112_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(add_default_category),
        migrations.AddField(
            model_name='spendingtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.SpendingCategory'),
        ),
    ]
